version: "3.8"
services:

  server:
    image: tensorflow/serving:2.1.0
    ports:
        - 8501:8501
    environment: 
        - MODEL_NAME=mnist
    volumes: 
        - ./model_files:/models/mnist

  client:
    image: tensorflow/tensorflow:2.1.0-py3-jupyter
    ports:
        - "8888:8888"
    volumes:
        - ./:/tf/mnist-server
    environment:
        - JUPYTER_TOKEN=letmein
    depends_on: 
        - server
